; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:blackpill_f401cc]
platform = ststm32
framework = stm32cube
board = blackpill_f401cc
board_build.f_cpu = 25000000L
extra_scripts = post:generate_hex.py
; lib_deps = electroniccats/MPU6050@^1.4.4
debug_tool = stlink
upload_protocol = stlink
build_flags =
    -Isrc/USB_DEVICE/
	-Isrc/MPU6050/
	-Wl,-Map=output.map
	;-u _printf_float	;futuramente remover
